### Importing necessary packages

In [1]:
import numpy as np
import numpy.linalg as la

### Implementing the Function to check Matrix Singularity

In [2]:
# Functions to fix each row and convert the matrix to echelon form
def fix_Row_Zero(A) :
    if A[0,0] == 0 :
        A[0] = A[0] + A[1]
    if A[0,0] == 0 :
        A[0] = A[0] + A[2]
    if A[0,0] == 0 :
        A[0] = A[0] + A[3]
    if A[0,0] == 0 :
        raise Matrix_Singular()
    A[0] = A[0] / A[0,0]
    return A

def fix_Row_One(A) :
    A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        raise Matrix_Singular()
    A[1] = A[1] / A[1,1]
    return A

def fix_Row_Two(A) :
    A[2] = A[2] - A[2,0] * A[0]
    A[2] = A[2] - A[2,1] * A[1]
    if A[2,2] == 0 :
        A[2] = A[2] + A[3]
        A[2] = A[2] - A[2,0] * A[0]
        A[2] = A[2] - A[2,1] * A[1]
        
    if A[2,2] == 0 :
        raise Matrix_Singular()
    A[2] = A[2] / A[2,2]
    return A

def fix_Row_Three(A) :
    A[3] = A[3] - A[3,0] * A[0]
    A[3] = A[3] - A[3,1] * A[1]
    A[3] = A[3] - A[3,2] * A[2]
    
    if A[3,3] == 0:
        raise Matrix_Singular()
    A[3] = A[3] / A[3,3]
    return A

In [3]:
"""

A function to test if a 4×4 matrix is singular, i.e. to determine if an inverse exists, before calculating it.

Used the method of converting a matrix to echelon form, and testing if this fails by leaving zeros that can’t be removed on the leading diagonal.

"""

def Singularity_Test(A) :
    B = np.array(A, dtype=np.float_)
    try:
        fix_Row_Zero(B)
        fix_Row_One(B)
        fix_Row_Two(B)
        fix_Row_Three(B)
    except Matrix_Singular:
        return True
    return False

# Error Flag
class Matrix_Singular(Exception): pass


In [4]:
# Verifying the results
A = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float_)
Singularity_Test(A)

True

In [5]:
B = np.array([[2,3,4,5],[5,4,9,7],[3,2,5,6],[9,9,6,5]],dtype=np.float_)
Singularity_Test(B)

False

In [6]:
fix_Row_Zero(B)

array([[1. , 1.5, 2. , 2.5],
       [5. , 4. , 9. , 7. ],
       [3. , 2. , 5. , 6. ],
       [9. , 9. , 6. , 5. ]])

In [7]:
fix_Row_One(B)

array([[ 1.        ,  1.5       ,  2.        ,  2.5       ],
       [-0.        ,  1.        ,  0.28571429,  1.57142857],
       [ 3.        ,  2.        ,  5.        ,  6.        ],
       [ 9.        ,  9.        ,  6.        ,  5.        ]])

In [8]:
fix_Row_Two(B)

array([[ 1.        ,  1.5       ,  2.        ,  2.5       ],
       [-0.        ,  1.        ,  0.28571429,  1.57142857],
       [-0.        , -0.        ,  1.        , -8.5       ],
       [ 9.        ,  9.        ,  6.        ,  5.        ]])

In [9]:
fix_Row_Three(B)

array([[ 1.        ,  1.5       ,  2.        ,  2.5       ],
       [-0.        ,  1.        ,  0.28571429,  1.57142857],
       [-0.        , -0.        ,  1.        , -8.5       ],
       [-0.        , -0.        , -0.        ,  1.        ]])

### Implementing the Gram Schmidt Process
Implementing a function to perform the Gram-Schmidt procedure, which takes a list of vectors and forms an orthonormal basis from this set.
As a corollary, the procedure allows us to determine the dimension of the space spanned by the basis vectors, which is equal to or less than the space which the vectors sit.

In [10]:
# Defining a very small number for comparison
verySmallNumber = 1e-14 # That's 1×10⁻¹⁴ = 0.00000000000001

In [11]:
def Gram_Schmidt_Basis(A) :
    B = np.array(A, dtype=np.float_)
    for i in range(B.shape[1]) :
        for j in range(i) :
            B[:, i] = B[:, i] - B[:, i] @ B[:, j] * B[:, j]
        if la.norm(B[:, i]) > verySmallNumber :
            B[:, i] = B[:, i] / la.norm(B[:, i])
        else :
            B[:, i] = np.zeros_like(B[:, i])    
    return B

In [12]:
def dimension_count(A) :
    """
    Function that uses the Gram-schmidt process to calculate the dimension spanned by a list of vectors.
    
    """
    return np.sum(la.norm(Gram_Schmidt_Basis(A), axis=0))

In [13]:
# Verifying the results
C = np.array([[1,0,2,6],[0,1,8,2],[2,8,3,1],[1,-6,2,3]], dtype=np.float_)
Gram_Schmidt_Basis(C)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [14]:
D = np.array([[1,0,2],[0,1,-3],[1,0,2]], dtype=np.float_)
Gram_Schmidt_Basis(D)

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        ]])

In [15]:
dimension_count(D)

2.0